apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuredisk
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "sc_name"
  resources:
    requests:
      storage: 5Gi